---
version: 2
before:
  hooks:
    - make service-prep

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    dir: service
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - "ghcr.io/jamesread/sickrock:{{ .Tag }}"
      - "ghcr.io/jamesread/sickrock:latest"

    dockerfile: Dockerfile
    extra_files:
      - frontend/dist
    skip_push: false
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.version={{.Tag}}"
